doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'

urlpatterns = [
    path('',views.index, name='index'),
    path('login',views.login, name='login'),
    path('register',views.register, name='register'),
]

hospitalerp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/',include('doctor.urls')),
    path('patients/',include('patients.urls')),
    path('nurse/',include('nurse.urls')),
    ]

nurse/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('duty',views.duty)
]

patients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home',views.home)
]

doctor/models.py
from django.db import models

# Create your models here.

nurse/models.py
from django.db import models

# Create your models here.

patients/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
# def index(request):
#     return HttpResponse('this is doctor module')
def index(request):
    return render(request, 'doctor_templates/home.html')


def login(request):
    return render(request,'doctor_templates/login.html')


def register(request):
    return render(request,'doctor_templates/register.html')

nurse/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def duty(request):
    return HttpResponse('nurse home screen')

patients/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return HttpResponse('patients home screen')

doctor/templates/doctor_templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'doctor:index' %}"> <input type="button"vale="register"></a>
    <a href="{% url 'doctor:index' %}"><input type="button"vale="register"></a>
    <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas porro, corporis repellendus nobis voluptatibus omnis provident! Asperiores corporis atque molestiae praesentium illum ad beatae nostrum, dolores saepe exercitationem! Beatae, commodi?</h1>
    <img src="{% static 'images/tree.jpg' %}" alt="">
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque sit atque ex animi incidunt, deleniti facere soluta unde error accusamus suscipit expedita maxime necessitatibus minima numquam, molestias eos laborum totam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus sit qui assumenda eligendi hic quasi atque fugit quo! Maiores ipsum sit officia soluta! Dolore esse ad dicta ratione ducimus vel.</p>
    hello
</body>
</html>

doctor/templates/doctor_templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text"placeholder="enter email">
    <input type="text"placeholder="enter password">
    <a href="{% url 'doctor:index' %}"><input type="button" value="log in"></a>
    <img src="{% static 'images/graphics.jpg' %}" alt="" width="20%" height="20%">
    
    
</body>
</html>

doctor/templates/doctor_templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <input type="text"placeholder="enter your name">
    <input type="text"placeholder="enter your place">
    <input type="button"value="register">
</body>
</html>